#!/bin/bash

bin="chromium"
args=""

if [[ -n "$WAYLAND_DISPLAY" ]]; then
	args="$args -enable-features=UseOzonePlatform -ozone-platform=wayland"
fi

if dmesg | grep nouveau >/dev/null; then
	args="$args --ignore-gpu-blocklist"

	if [[ -n "$WAYLAND_DISPLAY" ]]; then
		bin="google-chrome-unstable"
	fi
fi

$bin $args $@
