#!/bin/bash

bin="chromium"
args=""

if [[ -n "$WAYLAND_DISPLAY" ]]; then
	args="$args -enable-features=UseOzonePlatform,WebUIDarkMode -ozone-platform=wayland --force-dark-mode --profile-directory=Default --ignore-gpu-blocklist --enable-features=WebUIDarkMode,VaapiVideoEncoder"
fi

exec nice -5 $bin $args $@
